name: openreads
description: A mobile books tracker written in Flutter. Free, private and open source.

publish_to: "none"

version: 2.10.0+58

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.1.0
  path_provider: ^2.0.11
  rxdart: ^0.28.0
  path: ^1.9.0
  flutter_displaymode: ^0.6.0
  image_picker: ^1.0.0
  image_cropper: ^9.0.0
  flutter_bloc: ^9.0.0
  blurhash:
    git:
      url: https://github.com/mateusz-bak/blurhash.git
      ref: master
  image: ^4.0.15
  fl_chart: ^0.70.2
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  connectivity_plus: ^6.0.1
  http: ^1.2.0
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.2.0+3
  infinite_scroll_pagination: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  settings_ui: ^2.0.2
  url_launcher: ^6.1.6
  font_awesome_flutter: ^10.2.1
  hydrated_bloc: ^10.0.0
  barcode_scan2: ^4.2.1
  flutter_email_sender: ^6.0.0
  permission_handler: ^11.0.0
  filesystem_picker: ^4.0.0
  archive: ^4.0.2
  share_plus: ^10.0.2
  device_info_plus: ^11.2.2
  dynamic_color: ^1.6.2
  image_fade: ^0.6.2
  package_info_plus: ^8.0.0
  animated_widgets: ^1.1.0
  shared_preferences: ^2.2.1
  easy_localization: ^3.0.7
  flutter_typeahead: ^5.0.1
  flex_color_picker: ^3.2.2
  diacritic: ^0.1.4
  flutter_speed_dial: ^7.0.0
  blurhash_dart: ^1.2.1
  csv: ^6.0.0
  file_picker: ^8.3.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  dotted_border: ^2.1.0
  flutter_cache_manager: ^3.3.1
  modal_bottom_sheet: ^3.0.0
  saf_stream: ^0.11.1
  saf_util: ^0.6.2
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "./assets/icons/icon.png"
  adaptive_icon_foreground: "./assets/icons/icon.png"
  adaptive_icon_background: "#00BFA6"
  min_sdk_android: 21
  android: "launcher_icon"
  ios: true
  image_path_ios: "./assets/icons/gplay-icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: SofiaSans
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf
        - asset: assets/fonts/SofiaSans-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
    - family: AtkinsonHyperlegible
      fonts:
        - asset: assets/fonts/Atkinson-Hyperlegible-Regular-102.ttf
        - asset: assets/fonts/Atkinson-Hyperlegible-Bold-102.ttf
          weight: 700
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic3-Regular.ttf
        - asset: assets/fonts/OpenDyslexic3-Bold.ttf
          weight: 700
