name: Test build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android_apk_build:
    name: Android apk
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Flutter version
      run: echo "VERSION=$(cat .flutter-version)" >> $GITHUB_ENV

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.VERSION }}

    - name: Remove signing config
      run: awk '/release \{/ {f=1} !f; /}/ && f {f=0}' build.gradle > temp && mv temp build.gradle
      working-directory: android/app

    - name: Configure Flutter
      run: flutter config --no-analytics

    - name: Get Flutter packages
      run: flutter pub get

    - name: Build APK
      run: flutter build -v apk

  android_appbundle_build:
    name: Android appbundle
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Flutter version
      run: echo "VERSION=$(cat .flutter-version)" >> $GITHUB_ENV

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.VERSION }}

    - name: Remove signing config
      run: awk '/release \{/ {f=1} !f; /}/ && f {f=0}' build.gradle > temp && mv temp build.gradle
      working-directory: android/app

    - name: Configure Flutter
      run: flutter config --no-analytics

    - name: Get Flutter packages
      run: flutter pub get

    - name: Build appbundle
      run: flutter build -v appbundle

  ios_build:
    name: iOS ipa
    runs-on: macos-14
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Flutter version
      run: echo "VERSION=$(cat .flutter-version)" >> $GITHUB_ENV

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.VERSION }}

    - name: Configure Flutter
      run: flutter config --no-analytics

    - name: Get Flutter packages
      run: flutter pub get

    - name: Build iOS
      run: flutter build ios --no-codesign

  linux_build:
    name: Linux executable
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgtk-3-dev

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.VERSION }}
        cache: true

    - name: Configure Flutter
      run: |
        flutter config --no-analytics
        flutter config --enable-linux-desktop

    - name: Get Flutter packages
      run: flutter pub get

    - name: Build Linux
      run: flutter build --verbose linux --debug

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-appbundle
        path: build/linux/x64/debug/bundle/